=== SKupreeva/University/3 course/1 semester/SITAIRIS/Lab 4-5/order.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xlmns:xs = "http://www.w3.org/2001/XMLSchema">
    <xs:element name="order">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="client_info">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="gender" type="xs:string"/>
                            <xs:element name="age" type="xs:int"/>
                            <xs:element name="location" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="order_info">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="order_structure" type="xs:string"/>
                            <xs:element name="price" type="xs:positiveInteger"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="order_id" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== SKupreeva/University/3 course/1 semester/SITAIRIS/Lab 4-5/order.xml
<?xml version="1.0" encoding="UTF-8"?>

<order order_id = "346712" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="order.xsd">
    <client_info>
        <name>Johanes</name>
        <age>19</age>
        <gender>male</gender>
        <location>34-th street, 124 - New York, USA</location>
    </client_info>
    <order_info>
        <order_structure>Coca-Cola, Pizza, Sandwich</order_structure>
        <price>423</price>
    </order_info>
</order>
